### ISSUE TITLE
「/join」時のエラー

### ISSUE THREAD

**Issue by teobject** [ciffelia/koe#84]
ボイスチャンネルに接続しようとすると、下記のエラーが発生しております。
RTP接続エラーでセッションIDの問題であるのはわかるのですが、
https://discord.com/developers/ でアプリケーションの作り直しやサーバーを変えてみても同じエラーでして、
Discord側の問題なのか、使っているライブラリの問題なのか、原因の特定に難航しております。
よろしければ、少しお力添え頂けますと幸いです。

`{"@timestamp":"2023-04-08T13:15:52.837093053Z","log.level":"ERROR","message":"Failed to respond to slash command\n\nCaused by:\n    0: Failed to execute /join\n    1: failed to join voice channel: establishing connection failed\n    2: failed to connect to Discord RTP server: websocket issue (WsClosed(Some(CloseFrame { code: Library(4006), reason: \"Session is no longer valid.\" }))).","ecs.version":"1.12.1","log.origin":{"file":{"line":7,"name":"error.rs"},"rust":{"target":"koe::error","module_path":"koe::error","file_path":"crates/koe/src/error.rs"}}}`

**Comment by ciffelia** [comment]
ご報告ありがとうございます。こちらの環境でも再現しました。
以前までは動作していたことから、Discordの仕様変更が原因ではないかと考えています。調査の上修正します。

**Comment by ciffelia** [comment]
Discordから送られるデータの種類が増えたことで、Koeが依存しているライブラリであるSongbirdでエラーが発生するようになったようです。

https://github.com/serenity-rs/songbird/issues/172

Songbirdでは既にパッチがマージされており、近いうちに修正版がリリースされると思われます。そちらがリリースされ次第Koeでも修正版をリリースします。

**Comment by ciffelia** [comment]
この問題を修正したv1.1.0をリリースしました。アップデートをお願いします。

https://github.com/ciffelia/koe/releases/tag/1.1.0

**Comment by teobject** [comment]
ご丁寧に特定のライブラリまでお教え頂きありがとうございます。
修正助かります。
